# -*- coding: utf-8 -*-
"""mnist_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiScjDwZfis5MP0Ky-dvYSqIct0H4rxQ
"""

import tensorflow as tf
from tensorflow import keras

tf.__version__
keras.__version__

fashion_mnist=keras.datasets.fashion_mnist
(x_train_full,y_train_full) ,(x_test,y_test)=fashion_mnist.load_data()

x_train_full.shape

x_train_full.dtype

x_valid,x_train=x_train_full[:5000]/255.0 , x_train_full[5000:]/255.0

y_valid,y_train=y_train_full[:5000],y_train_full[5000:]

class_names=["Tshirt/top","Trouser","Pullover","Dress","Coat","Sandal","Shirt","Sneaker","Bag","AnkleBoot"]

class_names[y_train[0]]

model=keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dense(300,activation="relu"),
    keras.layers.Dense(100,activation="relu"),
    keras.layers.Dense(10,activation="softmax")
])

model.summary()

model.layers

hidden1=model.layers[1]

hidden1.name

model.get_layer("dense") is hidden1

weights,biases=hidden1.get_weights()

weights

weights.shape

biases

biases.shape

model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

History=model.fit(x_train,y_train,epochs=30,validation_data=(x_valid,y_valid))

import pandas as pd
import matplotlib.pyplot as plt
pd.DataFrame(History.history).plot(figsize=(8,5))
plt.grid(True)
plt.gca().set_ylim(0,1)
plt.show()

x_new=x_test[:3]
y_proba=model.predict(x_new)
y_proba.round(2)

y_pred=model.predict(x_new)
y_pred

y_new=y_test[:3]
y_new

